### ISSUE TITLE
Day 11 Task Submission

### ISSUE THREAD

**Issue by ikechukwu-anowe** [fbdevcowerri/git-14days-challenge#158]

**Comment by kodekage** [comment]
@anowe-godspower please don't create an issue when you submit a PR

**Comment by ikechukwu-anowe** [comment]
It's exactly what Ndubuisi Onyemenam preferred recommended when he started.
  Issokay, I'll stop.

**Comment by ikechukwu-anowe** [comment]
My Day 11 Challenge Pull Request is still among the 19 pull request that's
still open, it has not been merged.
  I'm waiting for it b4 I start day 12
