### ISSUE TITLE
I suggest we use Cloudinary for hosting our images so that the issues section will not get cluttered, or is there any advantage(s) "issues" have over Cloudinary?

### ISSUE THREAD

**Issue by ugwulo** [fbdevcowerri/git-14days-challenge#37]

**Comment by prondubuisi** [comment]
Hello @ugwulo , that's  a good suggestion! I think Github issues are easier as you don't have to create additional accounts. If you can share a Cloudinary link that would be great! The cloudinary solution will even be cleaner! +1 for that.

**Comment by ugwulo** [comment]
@prondubuisi ,I cannot share a cloudinary link because it requires an advanced plan.
Anyways, we can still stick with the issues directory to avert additional complexity.

**Comment by prondubuisi** [comment]
@ugwulo the free plan allowed sharing of links previously.
