### ISSUE TITLE
Upload images here for  challenges

### ISSUE THREAD

**Issue by prondubuisi** [fbdevcowerri/git-14days-challenge#5]
# Github Profile
![Github profile](https://user-images.githubusercontent.com/22311928/80335380-07ebb000-884c-11ea-9f7e-e6fba159b9a8.png)
# Github Repo
![Not forked repo](https://user-images.githubusercontent.com/22311928/80335383-091cdd00-884c-11ea-8d39-fbe9331f47de.png)
# Forked Repo
![Forked repo](https://user-images.githubusercontent.com/22311928/80335377-0621ec80-884c-11ea-9ae4-3c7ce33f692d.png)
# My local clone copy
![Local Clone](https://user-images.githubusercontent.com/22311928/80335544-7fb9da80-884c-11ea-8776-a00e4ed9f006.png)

**Comment by prondubuisi** [comment]
`
![Day2 see remotes](https://user-images.githubusercontent.com/22311928/80492186-93a03200-895b-11ea-8f19-f57a7117968c.png)
![Day 2  see new remotes](https://user-images.githubusercontent.com/22311928/80492200-969b2280-895b-11ea-94fd-ffea6be44438.png)
![Day 2 pull](https://user-images.githubusercontent.com/22311928/80492193-94d15f00-895b-11ea-87f5-651cd7d6458f.png)
![Day 2 Push](https://user-images.githubusercontent.com/22311928/80492197-96028c00-895b-11ea-8d2c-693ac994b476.png)

**Comment by amadikwajoyn** [comment]
**### Github Profile**

![githubRep](https://user-images.githubusercontent.com/20610726/80524499-92afd600-8944-11ea-8d78-834cbaeec42e.PNG)

**Comment by amadikwajoyn** [comment]
### My Github Repo

![forked repo](https://user-images.githubusercontent.com/20610726/80524835-1f5a9400-8945-11ea-91bd-603f64951456.PNG)

**Comment by amadikwajoyn** [comment]
### Github Forked Repo

![repoforked](https://user-images.githubusercontent.com/20610726/80524915-4618ca80-8945-11ea-866d-bc603c4ad98b.PNG)

**Comment by amadikwajoyn** [comment]
### Github Clone Repo

![cloneRepo](https://user-images.githubusercontent.com/20610726/80525036-77919600-8945-11ea-8d18-e51d5a296316.PNG)

**Comment by andemosa** [comment]
![Repo](https://user-images.githubusercontent.com/33299704/80659439-e6273e80-8a80-11ea-8e12-3e32eefd4e52.jpg)
![Fork](https://user-images.githubusercontent.com/33299704/80659444-e8899880-8a80-11ea-8880-c6d56051d778.jpg)
![Local](https://user-images.githubusercontent.com/33299704/80659445-e9bac580-8a80-11ea-83b2-fbf8dfd78347.jpg)

**Comment by andemosa** [comment]
My Repo
![Repo](https://user-images.githubusercontent.com/33299704/80659482-00611c80-8a81-11ea-8a30-b5c23476a0af.jpg)
Local clone
![Local](https://user-images.githubusercontent.com/33299704/80659480-ff2fef80-8a80-11ea-9b7b-bcca9bb18f7b.jpg)
Forked Repo
![Fork](https://user-images.githubusercontent.com/33299704/80659476-fb9c6880-8a80-11ea-84f1-a09d648cbb97.jpg)

**Comment by ugwulo** [comment]
# Git log screen grab
![gitLog](https://user-images.githubusercontent.com/52312550/80663860-11178f80-8a8d-11ea-8906-e9ce3523b83d.PNG)

# Git status screen grab
![gitStatus](https://user-images.githubusercontent.com/52312550/80663872-1a086100-8a8d-11ea-9f88-db9c425c0216.PNG)

# Command Editor screen grab
![commandEditor](https://user-images.githubusercontent.com/52312550/80663944-53d96780-8a8d-11ea-9dba-7ec7af0adebf.PNG)

**Comment by ugwulo** [comment]
![markdownScreenshot](https://user-images.githubusercontent.com/52312550/80769363-d96c1e80-8b44-11ea-9fc7-2b5d58d4f4f9.PNG)

**Comment by GodfirstOnuoha** [comment]
# GitHub Profile
![GitHub Profile](https://user-images.githubusercontent.com/52785343/80774514-27891e00-8b55-11ea-8da8-5dae74d3c0ef.PNG)

**Comment by GodfirstOnuoha** [comment]
# GitHub Repo
![Not Forked Repo](https://user-images.githubusercontent.com/52785343/80774576-57382600-8b55-11ea-95ce-06b0658aa580.PNG)

**Comment by GodfirstOnuoha** [comment]
# Forked Repo
![Forked Repo](https://user-images.githubusercontent.com/52785343/80774628-720a9a80-8b55-11ea-8a6d-6d90547fce79.PNG)

**Comment by GodfirstOnuoha** [comment]
# My Local Clone Copy
![Local Repo](https://user-images.githubusercontent.com/52785343/80774659-8484d400-8b55-11ea-98e6-538ec4dbb163.PNG)

**Comment by GodfirstOnuoha** [comment]
![Git Remote -v screenshot](https://user-images.githubusercontent.com/52785343/80774706-a41bfc80-8b55-11ea-8a17-7b00dd3b03ea.PNG)
![Git new remote screenshot](https://user-images.githubusercontent.com/52785343/80774741-bb5aea00-8b55-11ea-961c-0877d0af596b.PNG)
![Git pull screenshot](https://user-images.githubusercontent.com/52785343/80774748-c0b83480-8b55-11ea-8c31-8fa7b182dea9.PNG)
![Git push screenshot](https://user-images.githubusercontent.com/52785343/80774752-c3b32500-8b55-11ea-97ab-5772ca024bd1.PNG)

**Comment by GodfirstOnuoha** [comment]
![Git log](https://user-images.githubusercontent.com/52785343/80775120-a763b800-8b56-11ea-9025-6f60bb00775a.PNG)
![Git status](https://user-images.githubusercontent.com/52785343/80775186-d548fc80-8b56-11ea-84a9-92339781202a.PNG)
![Open Editor](https://user-images.githubusercontent.com/52785343/80775997-1fcb7880-8b59-11ea-92b7-d6f4a0e4d588.PNG)

**Comment by GodfirstOnuoha** [comment]
![Markdown Screenshot](https://user-images.githubusercontent.com/52785343/80778298-d29ed500-8b5f-11ea-8b70-a0821f184565.PNG)

**Comment by vinuch** [comment]
![image](https://user-images.githubusercontent.com/44481619/80925987-16a0fe00-8d49-11ea-9c3d-0383fb728eb1.png)
![image](https://user-images.githubusercontent.com/44481619/80926014-40f2bb80-8d49-11ea-819e-3da2104da05a.png)
![image](https://user-images.githubusercontent.com/44481619/80926041-6b447900-8d49-11ea-9172-fba8bd659858.png)

**Comment by vinuch** [comment]
![image](https://user-images.githubusercontent.com/44481619/80926110-e3ab3a00-8d49-11ea-8e76-69c0b3927d55.png)

**Comment by vinuch** [comment]
![image](https://user-images.githubusercontent.com/44481619/80926352-a2b42500-8d4b-11ea-87d3-0d78434dabcd.png)
![image](https://user-images.githubusercontent.com/44481619/80926356-a8aa0600-8d4b-11ea-99c2-a2881e33bce0.png)

**Comment by vinuch** [comment]
![image](https://user-images.githubusercontent.com/44481619/80926401-e9098400-8d4b-11ea-9f27-5daf7beda42b.png)
![image](https://user-images.githubusercontent.com/44481619/80926515-abf1c180-8d4c-11ea-8831-78751907aef2.png)

![image](https://user-images.githubusercontent.com/44481619/80927659-1ce8a780-8d54-11ea-82e6-907fbf1c41b0.png)


![image](https://user-images.githubusercontent.com/44481619/80926990-b19cd680-8d4f-11ea-8ef3-549d1b54fa28.png)

![image](https://user-images.githubusercontent.com/44481619/80927015-d98c3a00-8d4f-11ea-8ac1-43632942240a.png)

![image](https://user-images.githubusercontent.com/44481619/80927051-19ebb800-8d50-11ea-85d0-496e8be1e503.png)

**Comment by GodfirstOnuoha** [comment]
![Git remote -help screenshot](https://user-images.githubusercontent.com/52785343/81024782-6fb58280-8e6c-11ea-8818-7f3b3bf0ecb4.PNG)

![Another Git help screenshot](https://user-images.githubusercontent.com/52785343/81024804-7e9c3500-8e6c-11ea-9c70-0e068919813f.PNG)

![Git remote -v screenshot after additions](https://user-images.githubusercontent.com/52785343/81024950-f8ccb980-8e6c-11ea-8672-785dbb0a89d5.PNG)

![Git remote screenshot after remove and rename and set url](https://user-images.githubusercontent.com/52785343/81024841-92e03200-8e6c-11ea-87e3-793ad8d7938d.PNG)

![Final Screenshot](https://user-images.githubusercontent.com/52785343/81024856-9a9fd680-8e6c-11ea-8dd3-f00e92284f63.PNG)

**Comment by ugwulo** [comment]
![gitRemoteHelp](https://user-images.githubusercontent.com/52312550/81114681-68e54900-8f1a-11ea-8124-56c99d7df680.PNG)

![gitRemotes](https://user-images.githubusercontent.com/52312550/81114191-74844000-8f19-11ea-8589-3f6a55800dcd.PNG)
![gitRemotesFinal](https://user-images.githubusercontent.com/52312550/81114212-7fd76b80-8f19-11ea-82a7-21d77a888e13.PNG)

![gitRebaseHelp](https://user-images.githubusercontent.com/52312550/81114053-25d6a600-8f19-11ea-8da4-fc02b24113d8.PNG)

![blahblah](https://user-images.githubusercontent.com/52312550/81116146-c4183b00-8f1c-11ea-87cb-ff2188e98ba3.PNG)

**Comment by andemosa** [comment]
My Repo

![Repo](https://user-images.githubusercontent.com/33299704/81488327-45ded000-925f-11ea-8e7e-fd2b7bb7e8fe.jpg)

Forked Repo

![Fork](https://user-images.githubusercontent.com/33299704/81488328-47a89380-925f-11ea-8bb8-a52d5b8dc6af.jpg)

Cloned Local Repo

![Local](https://user-images.githubusercontent.com/33299704/81488329-48412a00-925f-11ea-9e29-f39f4fb5421e.jpg)
